"""empty message

Revision ID: b84fd86b9cbf
Revises: 
Create Date: 2022-05-03 12:28:38.445528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84fd86b9cbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Grupos',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['Usuarios.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('Eventos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('backgroundColor', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['grupo'], ['Grupos.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Grupo_User_Relation',
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('admin', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['grupo'], ['Grupos.name'], ),
    sa.ForeignKeyConstraint(['user'], ['Usuarios.name'], ),
    sa.PrimaryKeyConstraint('grupo', 'user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Grupo_User_Relation')
    op.drop_table('Eventos')
    op.drop_table('Grupos')
    op.drop_table('Usuarios')
    # ### end Alembic commands ###
